# Frontend
server {
  set $forward_scheme http;
  set $server "172.17.0.1";
  set $port 80;

  listen 80;
  listen [::]:80;

  server_name baotrang.io.vn;
  http2 off;

  access_log /dev/stdout combined;
  error_log /dev/stderr warn;

  include snippets/proxy-params.conf;

  location / {
    proxy_pass http://172.17.0.1:5732;
  }
}

# Backend
server {
  set $forward_scheme http;
  set $server "172.17.0.1";
  set $port 80;

  listen 80;
  listen [::]:80;

  server_name api.baotrang.io.vn;
  http2 off;

  access_log /dev/stdout combined;
  error_log /dev/stderr warn;

  include snippets/proxy-params.conf;

  location / {
    proxy_pass http://172.17.0.1:9999;
  }
}

# Minio UI
server {
  set $forward_scheme http;
  set $server "172.17.0.1";
  set $port 80;

  listen 80;
  listen [::]:80;

  server_name minio-ui.baotrang.io.vn;
  http2 off;

  access_log /dev/stdout combined;
  error_log /dev/stderr warn;

  include snippets/proxy-params.conf;

  location / {
    proxy_pass http://172.17.0.1:9001;
  }
}

# Minio API
server {
  set $forward_scheme http;
  set $server "172.17.0.1";
  set $port 80;

  listen 80;
  listen [::]:80;

  server_name minio.baotrang.io.vn;
  http2 off;

  access_log /dev/stdout combined;
  error_log /dev/stderr warn;

  include snippets/proxy-params.conf;

  location / {
    proxy_pass http://172.17.0.1:9000;
  }
}

# Jenkins
server {
  set $forward_scheme http;
  set $server "172.17.0.1";
  set $port 80;

  listen 80;
  listen [::]:80;

  server_name jenkins.baotrang.io.vn;
  http2 off;

  access_log /dev/stdout combined;
  error_log /dev/stderr warn;

  include snippets/proxy-params.conf;

  location / {
    proxy_pass http://172.17.0.1:8000;
  }
}

# Grafana
server {
  set $forward_scheme http;
  set $server "172.17.0.1";
  set $port 80;

  listen 80;
  listen [::]:80;

  server_name grafana.baotrang.io.vn;
  http2 off;

  access_log /dev/stdout combined;
  error_log /dev/stderr warn;

  include snippets/proxy-params.conf;

  location / {
    proxy_pass http://172.17.0.1:3000;
  }
}