# Global settings for all servers in this file
access_log  /dev/stdout combined;
error_log   /dev/stderr warn;
http2       off;

# Frontend
server {
  listen 80;
  listen [::]:80;
  server_name baotrang.io.vn;

  location / {
    include snippets/proxy-params.conf;
    proxy_pass http://172.17.0.1:5732;
  }
}

# Backend
server {
  listen 80;
  listen [::]:80;
  server_name api.baotrang.io.vn;

  location / {
    include snippets/proxy-params.conf;
    proxy_pass http://172.17.0.1:9999;
  }
}

# Minio UI
server {
  listen 80;
  listen [::]:80;
  server_name minio-ui.baotrang.io.vn;

  location / {
    include snippets/proxy-params.conf;
    proxy_pass http://172.17.0.1:9001;
  }
}

# Minio API
server {
  listen 80;
  listen [::]:80;
  server_name minio.baotrang.io.vn;

  location / {
    include snippets/proxy-params.conf;
    proxy_pass http://172.17.0.1:9000;
  }
}

# Jenkins
server {
  listen 80;
  listen [::]:80;
  server_name jenkins.baotrang.io.vn;

  location / {
    include snippets/proxy-params.conf;
    proxy_pass http://172.17.0.1:8000;
  }
}

# Grafana
server {
  listen 80;
  listen [::]:80;
  server_name grafana.baotrang.io.vn;

  location / {
    include snippets/proxy-params.conf;
    proxy_pass http://172.17.0.1:3000;
  }
}