version: "3.9"

services:
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus/config.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    ports:
      - "9090:9090"
    container_name: prometheus
    depends_on:
      - node-exporter
      - cadvisor
    restart: always

  grafana:
    image: grafana/grafana:latest
    volumes:
      - grafana-data:/var/lib/grafana
    ports:
      - "3000:3000"
    container_name: grafana
    depends_on:
      - prometheus
    restart: always

  node-exporter:
    image: prom/node-exporter:latest
    restart: always
    ports:
      - "9100:9100"
    container_name: node-exporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - "--path.procfs=/host/proc"
      - "--path.sysfs=/host/sys"
      - "--path.rootfs=/rootfs"
      - "--collector.filesystem.ignored-mount-points='^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)'"

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    ports:
      - "8080:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    container_name: cadvisor
    restart: always

  alertmanager:
    image: prom/alertmanager:latest
    volumes:
      - ./alertmanager/config.yml:/etc/alertmanager/alertmanager.yml
    ports:
      - "9093:9093"
    container_name: alertmanager
    restart: always

  mysql-exporter:
    image: prom/mysqld-exporter:latest
    ports:
      - "9104:9104"
    container_name: mysql-exporter
    restart: always
    command:
      - "--config.my-cnf=/.my.cnf"
    volumes:
      - ./mysql-exporter/.my.cnf:/.my.cnf

  loki:
    image: grafana/loki:latest
    ports:
      - "3100:3100"
    container_name: loki
    volumes:
      - ./loki/config.yml:/etc/loki/local-config.yaml
      - loki-data:/loki
    command: -config.file=/etc/loki/local-config.yaml
    restart: always

  # promtail:
  #   image: grafana/promtail:latest
  #   container_name: promtail
  #   volumes:
  #     - ./promtail/config.yml:/etc/promtail/config.yml
  #     - /var/log:/var/log:ro
  #     - /var/lib/docker/containers:/var/lib/docker/containers:ro
  #   command: -config.file=/etc/promtail/config.yml
  #   depends_on:
  #     - loki
  #   restart: always

  # tempo:
  #   image: grafana/tempo:2.6.1
  #   container_name: tempo
  #   ports:
  #     - "3200:3200"
  #     - "4317:4317"
  #     - "4318:4318"
  #   volumes:
  #     - ./tempo/config.yml:/etc/tempo/config.yml
  #     - tempo-data:/var/tempo
  #   command: -config.file=/etc/tempo/config.yml
  #   restart: always

volumes:
  prometheus-data:
  grafana-data:
  loki-data:
  # tempo-data:
