apiVersion: apps/v1
kind: Deployment
metadata:
  name: clusterip-app-deployment
  namespace: dev
spec:
  replicas: 3
  selector:
    matchLabels:
      app: dev-app
  template:
    metadata:
      labels:
        app: dev-app
    spec:
      containers:
        - name: app-container
          image: vietaws/eks:v1
          ports:
            - containerPort: 8080
          env:
            - name: APP_NAME
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: app-name
            - name: SECRET_USERNAME
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: username
            - name: SECRET_APP_NAME_STRING_DATA
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: app-name-string-data
          resources:
            # Recommended
            requests:
              memory: "128Mi"
              cpu: "256m"
            limits:
              memory: "128Mi"
              # cpu: "512m"
