def telegram

pipeline {
  agent any

  environment {
    REPO_URL           = 'https://github.com/maituananh/pawn-service-fe'
    BRANCH             = 'main'
    APP_NAME           = 'frontend-pawn-app'

    TELEGRAM_BOT_TOKEN = credentials('TELEGRAM_BOT_TOKEN')
    TELEGRAM_CHAT_ID   = credentials('TELEGRAM_CHAT_ID')
    DOCKER_USER        = credentials('DOCKER_USER')
    DOCKER_PASS        = credentials('DOCKER_PASS')
    DOCKERHUB_REPO     = credentials('DOCKERHUB_REPO_FE')
    FE_PORT            = credentials('FE_PORT')
    VITE_API_BASE_URL  = credentials('API_BASE_URL')
  }

  triggers {
    // githubPush()
    GenericTrigger(
      genericVariables: [
        [key: 'GITHUB_PR_ACTION',   value: '$.action',                defaultValue: ''],
        [key: 'GITHUB_PR_MERGED',   value: '$.pull_request.merged',   defaultValue: 'false'],
        [key: 'GITHUB_PR_BASE_REF', value: '$.pull_request.base.ref', defaultValue: ''],
        [key: 'GITHUB_REPO_NAME',   value: '$.repository.full_name',  defaultValue: ''],
      ],
      causeString: 'Triggered by GitHub webhook',
      printContributedVariables: true,
      printPostContent: true
    )
  }

  tools {
    nodejs 'nodejs22.14.0'
  }

  stages {
    stage('Checkout') {
      steps {
        script {
          telegram = load 'jenkins/shared/telegram.groovy'
        }
        deleteDir()

        git branch: "${BRANCH}", url: "${REPO_URL}"
      }
    }

    stage('Install Dependencies') {
      steps {
        sh 'npm install'
      }
    }

    stage('Test') {
      steps {
        sh 'npm test'
      }
    }

    stage('Build') {
      environment {
        NODE_ENV = 'production'
      }

      steps {
        sh 'npm run build'
      }
    }

    stage('Debug Payload') {
      steps {
        echo "env.GITHUB_PR_ACTION: ${env.GITHUB_PR_ACTION}"
        echo "env.GITHUB_PR_MERGED: ${env.GITHUB_PR_MERGED}"
        echo "env.GITHUB_PR_BASE_REF: ${env.GITHUB_PR_BASE_REF}"
        echo "env.GITHUB_REPO_NAME: ${env.GITHUB_REPO_NAME}"
        echo "env.BRANCH: ${env.BRANCH}"
      }
    }

    stage('Build Docker Image') {
      steps {
        script {
          // Generate timestamp
          def timestamp = sh(
            script: 'date +%Y%m%d%H%M%S',
                returnStdout: true
            ).trim()

            env.IMAGE_TAG = timestamp

            sh """
            docker build \\
              --build-arg VITE_API_BASE_URL=\${API_BASE_URL} \\
              -t \${DOCKERHUB_REPO}:\${IMAGE_TAG} .
            """
        }
      }
    }

    stage('Push Docker Image') {
      when {
        expression {
          return env.GIT_BRANCH == 'origin/main'
        }
      }

      steps {
        script {
          sh """
            echo "\${DOCKER_PASS}" | docker login -u "\${DOCKER_USER}" --password-stdin
            docker push \${DOCKERHUB_REPO}:\${IMAGE_TAG}
            """

          // Cleanup local images (keep 3 latest)
          sh """
            docker images \${DOCKERHUB_REPO} --format "{{.Tag}}" | \\
            sort -r | tail -n +4 | xargs -r -I {} docker rmi \${DOCKERHUB_REPO}:{} || true
            """
        }
      }
    }

    stage('Pull Docker Image') {
      when {
        expression {
          return env.GIT_BRANCH == 'origin/main'
        }
      }

      steps {
        script {
          sh """
          docker pull \${DOCKERHUB_REPO}:\${IMAGE_TAG}
          """
        }
      }
    }

    stage('Deploy') {
      when {
        expression {
          return env.GIT_BRANCH == 'origin/main'
        }
      }

      steps {
        script {
          sh """
          echo "\${DOCKER_PASS}" | docker login -u "\${DOCKER_USER}" --password-stdin

          docker stop ${APP_NAME} || true
          docker rm ${APP_NAME} || true
          docker run -d \\
            --name ${APP_NAME} \\
            -p \${FE_PORT}:80 \\
            -e VITE_API_BASE_URL=\${API_BASE_URL} \\
            \${DOCKERHUB_REPO}:\${IMAGE_TAG}
          """
        }
      }
    }
  }

  post {
    always {
      script {
        if (currentBuild.currentResult == 'FAILURE') {
          telegram('FAILURE', env.BRANCH)
        }
        else if (currentBuild.currentResult == 'SUCCESS') {
          telegram('SUCCESS', env.BRANCH)
        }
        else if (currentBuild.currentResult == 'ABORTED') {
          telegram('ABORTED', env.BRANCH)
        }
        else {
          telegram('UNSTABLE', env.BRANCH)
        }
      }
    }
  }
}
