def telegram

pipeline {
  agent any

  environment {
    REPO_URL           = 'https://github.com/maituananh/backend'
    BRANCH             = 'anhkiet-branch'
    APP_NAME           = 'backend-pawn-app'
    CICD_REPO_NAME     = 'maituananh/pawn-service-cicd'
    REPO_URL_CICD      = 'https://github.com/maituananh/pawn-service-cicd'

    // System key
    TELEGRAM_BOT_TOKEN = credentials('TELEGRAM_BOT_TOKEN')
    TELEGRAM_CHAT_ID   = credentials('TELEGRAM_CHAT_ID')
    DOCKER_USER        = credentials('DOCKER_USER')
    DOCKER_PASS        = credentials('DOCKER_PASS')
    DOCKERHUB_REPO     = credentials('DOCKERHUB_REPO_BE')
    SECRET_TOKEN_BE    = credentials('SECRET_TOKEN_BE')

    // Backend key
    BE_PORT               = credentials('BE_PORT')
    AWS_S3_ENDPOINT       = credentials('AWS_S3_ENDPOINT')
    STRIPE_API_KEY        = credentials('STRIPE_API_KEY')
    STRIPE_WEBHOOK_SECRET = credentials('STRIPE_WEBHOOK_SECRET')
    AI_OPENAI_API_KEY     = credentials('AI_OPENAI_API_KEY')
    DB_HOST               = credentials('DB_HOST') // docker ip
    REDIS_HOST            = credentials('REDIS_HOST') // docker ip
  }

  triggers {
    // githubPush()
    GenericTrigger(
      genericVariables: [
        [key: 'GITHUB_PR_ACTION',   value: '$.action',                defaultValue: ''],
        [key: 'GITHUB_PR_MERGED',   value: '$.pull_request.merged',   defaultValue: 'false'],
        [key: 'GITHUB_PR_BASE_REF', value: '$.pull_request.base.ref', defaultValue: ''],
        [key: 'GITHUB_REPO_NAME',   value: '$.repository.full_name',  defaultValue: ''],
      ],
      causeString: 'Triggered by GitHub webhook',
      tokenCredentialId: 'SECRET_TOKEN_BE',
      token: "SECRET_TOKEN_BE",
      printContributedVariables: true,
      printPostContent: true
    )
  }

  stages {
    stage('Checkout') {
      steps {
        script {
          telegram = load 'jenkins/shared/telegram.groovy'

          deleteDir()

          if (env.GITHUB_REPO_NAME == env.CICD_REPO_NAME) {
            git branch: "${BRANCH}", url: "${REPO_URL}"
          } else {
            git branch: "${env.GITHUB_PR_HEAD_REF}", url: "${REPO_URL}"
          }
        }
      }
    }

    stage('Build') {
      steps {
        sh 'chmod +x gradlew'
        sh './gradlew clean build -x test'
      }
    }

    stage('Test') {
      steps {
        sh './gradlew test'
      }
    }

    stage('Package') {
      steps {
        sh './gradlew bootJar'
      }
    }

    stage('Build Docker Image') {
      steps {
        script {
          def timestamp = sh(
            script: 'date +%Y%m%d%H%M%S',
                returnStdout: true
            ).trim()

            env.IMAGE_TAG = timestamp

            sh """
            docker build -t \${DOCKERHUB_REPO}:${IMAGE_TAG} .
            """
        }
      }
    }

    stage('Push Docker Image') {
      when {
        expression {
          return env.GITHUB_PR_MERGED == 'true'
        }
      }

      steps {
        script {
          sh """
            echo "\${DOCKER_PASS}" | docker login -u "\${DOCKER_USER}" --password-stdin
            docker push \${DOCKERHUB_REPO}:${IMAGE_TAG}
            """

          // Cleanup local images (keep 3 latest)
          sh """
            docker images \${DOCKERHUB_REPO} --format "{{.Tag}}" | \\
            sort -r | tail -n +4 | xargs -r -I {} docker rmi \${DOCKERHUB_REPO}:{} || true
            """
        }
      }
    }

    stage('Pull Docker Image') {
      when {
        expression {
          return env.GITHUB_PR_MERGED == 'true'
        }
      }

      steps {
        script {
          sh """
          docker pull \${DOCKERHUB_REPO}:${IMAGE_TAG}
          """
        }
      }
    }

    stage('Deploy') {
      when {
        expression {
          return env.GITHUB_PR_MERGED == 'true'
        }
      }

      steps {
        script {
          sh """
          echo "\${DOCKER_PASS}" | docker login -u "\${DOCKER_USER}" --password-stdin

          docker stop ${APP_NAME} || true
          docker rm ${APP_NAME} || true
          docker run -d \\
            --name ${APP_NAME} \\
            -p \${BE_PORT}:8080 \\
            -e SPRING_PROFILES_ACTIVE=prod \\
            -e DB_HOST=\${DB_HOST} \\
            -e AWS_S3_ENDPOINT=\${AWS_S3_ENDPOINT} \\
            -e STRIPE_API_KEY=\${STRIPE_API_KEY} \\
            -e STRIPE_WEBHOOK_SECRET=\${STRIPE_WEBHOOK_SECRET} \\
            -e AI_OPENAI_API_KEY=\${AI_OPENAI_API_KEY} \\
            -e REDIS_HOST=\${REDIS_HOST} \\
            \${DOCKERHUB_REPO}:${IMAGE_TAG}
          """
        }
      }
    }
  }

  post {
    always {
      script {
        if (currentBuild.currentResult == 'FAILURE') {
          telegram('FAILURE', "${env.GITHUB_PR_HEAD_REF}")
        }
        else if (currentBuild.currentResult == 'SUCCESS') {
          telegram('SUCCESS', "${env.GITHUB_PR_HEAD_REF}")
        }
        else if (currentBuild.currentResult == 'ABORTED') {
          telegram('ABORTED', "${env.GITHUB_PR_HEAD_REF}")
        }
        else {
          telegram('UNSTABLE', "${env.GITHUB_PR_HEAD_REF}")
        }
      }
    }
  }
}
