# Global settings for all servers in this file
access_log  /dev/stdout combined;
error_log   /dev/stderr warn;
http2       off;

upstream ingress_nginx {
  server master:31220;
  server worker1:31220;
  server worker2:31220;
}

server {
  listen 80;
  listen [::]:80;
  server_name _;  # wildcard

  location / {
    include snippets/proxy-params.conf;
    proxy_pass http://ingress_nginx;
  }
}
