# Global settings for all servers in this file
access_log  /dev/stdout combined;
error_log   /dev/stderr warn;
http2       off;

upstream my_servers {
    server 172.16.143.110:30080;
    server 172.16.143.111:30080;
    server 172.16.143.112:30080;
}

server {
  listen 80;

  location / {
    include snippets/proxy-params.conf;
    proxy_pass http://my_servers;
  }
}